### ISSUE TITLE
Fusion individuals/corporations ?

### ISSUE THREAD

**Issue by BenoitMC** [agilidee/dorsale#158]
Bon... ça fait un moment que ça me démange !

La séparation des individuals/corporations dans 2 tables c'est chiant : 

- Plein de champs sont dupliqués dans les deux tables, dès qu'on veut rajouter un truc on duplique
- On ne peut pas requêter sur les deux tables en même temps : on duplique la requête pour chacun, puis on merge les résultats en Ruby
- On est obligé de retrier à la main en ruby après les requêtes

Un exemple de truc horrible qu'on peut trouver : 

```ruby
@individuals  ||= policy_scope(::Dorsale::CustomerVault::Individual).search(params[:q])
@corporations ||= policy_scope(::Dorsale::CustomerVault::Corporation).search(params[:q])

if params[:q].blank?
  @individuals  = @filters.apply(@individuals)
  @corporations = @filters.apply(@corporations)
end

@people ||= @individuals + @corporations
@people = @people.sort_by(&:name)

@people = Kaminari.paginate_array(@people).page(params[:page]).per(25)
```

Par contre, certaines infos ne sont valables que pour les entreprises ou pour les individus, et ne font pas de sens dans l'autre model : siret, capital, ...

Ma proposition : 

- On met tout dans une seule table
- On fait 2 modèles avec un STI pour conserver la logique individual/corporation
- On serialize les données spécifiques en JSON dans un champ data

Ces données spécifiques sont généralement "secondaires" : on n'a jamais besoin de requêter dessus donc les mettre en JSON n'est pas gênant. Et s'il faut requêter dessus un jour, Postgresql gère ça très bien en permettant les requêtes sur du JSON dans un champ.

Qu'en pensez-vous ?

cc @agilidee/agilidee

**Comment by bgantaume** [comment]
Je vote pour!

Le 9 sept. 2016 4:58 PM, "Benoit MARTIN-CHAVE" <notifications@github.com> a
écrit :
