### ISSUE TITLE
Remplacer les CSV par des XLSX

### ISSUE THREAD

**Issue by BenoitMC** [agilidee/dorsale#163]
... Et gérer ça dans le vue et non dans les modèles ou les controllers.

@agilidee/agilidee Des objections ? Le CSV a une raison d'être ou c'est juste que c'était plus simple que du Excel avant ?

**Comment by BenoitMC** [comment]
Dans les tâches il y a un double export CSV + XLS.
Ca sert à quelqu'un à part pour Pilote ?
Je pense qu'un Excel suffit pour Dorsale.

**Comment by bgantaume** [comment]
Oui, un excel suffit est c'est plus standard.
