### ISSUE TITLE
Individual belongs_to Corporation ?

### ISSUE THREAD

**Issue by BenoitMC** [agilidee/dorsale#178]
C'est une demande récurrente, on l'a au moins dans Ekos et BuyCo.
On pourrait intégrer la relation dans Dorsale mais laisser facultatif, et rentre obligatoire en fonction des projets.
Par contre ce qui m'embête c'est que ça fait un peu doublon avec les liens.

Qu'en pensez-vous ?

cc @agilidee/agilidee

**Comment by bgantaume** [comment]
Le belong_to n'est jamais qu'un lien d'un type particulier...
Tu proposes de l'intégrer au niveau du modèle ou au niveau de la vue?

**Comment by BenoitMC** [comment]
Modèle

**Comment by BenoitMC** [comment]
Peut-être que la solution c'est plutôt d'intégrer les liens directement dans le formulaire des personnes au lieu d'avoir on controller dédié

**Comment by bgantaume** [comment]
Oui! Y'a de l'idée. Clairement.
