### ISSUE TITLE
Rajouter une valeur par défaut au helper "info"

### ISSUE THREAD

**Issue by marc-agilidee** [agilidee/dorsale#197]
Un truc qui ferait soit valeur par défaut, soit rien ne s'affiche, ca serait bien ;)

**Comment by BenoitMC** [comment]
@marc-agilidee 

Ce sera dispo dans la prochaine mise à jour de Dorsale.
Tu pourras aussi faire un `default: :hide` pour ne rien afficher du tout si c'est vide.
C'est également compatible avec les chaines de caractère vide ou "blank" et pas uniquement avec les valeurs nil.

**Comment by marc-agilidee** [comment]
T'es un boss !

2016-11-18 16:02 GMT+01:00 Benoit MARTIN-CHAVE <notifications@github.com>:
