### ISSUE TITLE
Breadcrumb ?

### ISSUE THREAD

**Issue by BenoitMC** [agilidee/dorsale#73]
Ils sont sur CustomerVault mais nul part ailleurs.
Faut-il les conserver et les généraliser ? Les supprimer ?

Je ne leur trouve pas une grande utilisé, on a rarement beaucoup de niveau, et les contextes aident à se situer.

**Comment by BenoitMC** [comment]
@bgantaume Je peux les virer ?

**Comment by bgantaume** [comment]
fais toi plaisir

**Comment by bgantaume** [comment]
pendant que tu y es, si tu nous fais passer les new du contexte vers le haut de liste, on sera raccord avec les autres écrans

**Comment by BenoitMC** [comment]
Bonne idée
